# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Blood Pressure App to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'bloodpressuredm'
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  Build_Sonar_Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: SonarCloud scanner
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=x00180709
            -Dsonar.projectKey=x00180709
            -Dsonar.python.coverage.reportPaths=covereage.xml
            -Dsonar.verbose=true
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test Unit_Tests/Unit_Tests.csproj --no-restore --collect "Code coverage" -l:trx

      - name: Publish the results of the Unit Test Execution run
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MS Tests
          path: '**.trx'
          reporter: 'dotnet-trx'

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_470A4E3A8794471282F0681E8F186702 }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
  
  K6_Load_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker image used for k6
      run: docker pull loadimpact/k6

    - name: Run load tests and save output
      run: docker run -i loadimpact/k6 run - <PerfTestCA1.js > k6output.txt

    - uses: actions/upload-artifact@v2
      with:
        name: k6output
        path: k6output.txt

  Dependency_Check:
    runs-on: ubuntu-latest

    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project
        run: dotnet build

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'BPCalculator'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports